# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import strategy_service_pb2 as strategy__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in strategy_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeSignals = channel.unary_unary(
                '/com.marketpredictor.grpc.StrategyService/ComputeSignals',
                request_serializer=strategy__service__pb2.SignalRequest.SerializeToString,
                response_deserializer=strategy__service__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.RecordTradeOutcome = channel.unary_unary(
                '/com.marketpredictor.grpc.StrategyService/RecordTradeOutcome',
                request_serializer=strategy__service__pb2.TradeOutcomeRequest.SerializeToString,
                response_deserializer=strategy__service__pb2.TradeOutcomeResponse.FromString,
                _registered_method=True)
        self.GetLearnerState = channel.unary_unary(
                '/com.marketpredictor.grpc.StrategyService/GetLearnerState',
                request_serializer=strategy__service__pb2.LearnerStateRequest.SerializeToString,
                response_deserializer=strategy__service__pb2.LearnerStateResponse.FromString,
                _registered_method=True)
        self.TrainOnSymbol = channel.unary_unary(
                '/com.marketpredictor.grpc.StrategyService/TrainOnSymbol',
                request_serializer=strategy__service__pb2.TrainingRequest.SerializeToString,
                response_deserializer=strategy__service__pb2.TrainingResponse.FromString,
                _registered_method=True)
        self.FetchLiveQuote = channel.unary_unary(
                '/com.marketpredictor.grpc.StrategyService/FetchLiveQuote',
                request_serializer=strategy__service__pb2.QuoteRequest.SerializeToString,
                response_deserializer=strategy__service__pb2.QuoteResponse.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeSignals(self, request, context):
        """Get strategy signals for current market state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTradeOutcome(self, request, context):
        """Record executed trade outcome for online learning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLearnerState(self, request, context):
        """Get current learner state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainOnSymbol(self, request, context):
        """Trigger offline historical training for a symbol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchLiveQuote(self, request, context):
        """Fetch near-real-time live quote from Yahoo Finance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeSignals,
                    request_deserializer=strategy__service__pb2.SignalRequest.FromString,
                    response_serializer=strategy__service__pb2.SignalResponse.SerializeToString,
            ),
            'RecordTradeOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTradeOutcome,
                    request_deserializer=strategy__service__pb2.TradeOutcomeRequest.FromString,
                    response_serializer=strategy__service__pb2.TradeOutcomeResponse.SerializeToString,
            ),
            'GetLearnerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLearnerState,
                    request_deserializer=strategy__service__pb2.LearnerStateRequest.FromString,
                    response_serializer=strategy__service__pb2.LearnerStateResponse.SerializeToString,
            ),
            'TrainOnSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainOnSymbol,
                    request_deserializer=strategy__service__pb2.TrainingRequest.FromString,
                    response_serializer=strategy__service__pb2.TrainingResponse.SerializeToString,
            ),
            'FetchLiveQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchLiveQuote,
                    request_deserializer=strategy__service__pb2.QuoteRequest.FromString,
                    response_serializer=strategy__service__pb2.QuoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.marketpredictor.grpc.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.marketpredictor.grpc.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.marketpredictor.grpc.StrategyService/ComputeSignals',
            strategy__service__pb2.SignalRequest.SerializeToString,
            strategy__service__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTradeOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.marketpredictor.grpc.StrategyService/RecordTradeOutcome',
            strategy__service__pb2.TradeOutcomeRequest.SerializeToString,
            strategy__service__pb2.TradeOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLearnerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.marketpredictor.grpc.StrategyService/GetLearnerState',
            strategy__service__pb2.LearnerStateRequest.SerializeToString,
            strategy__service__pb2.LearnerStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainOnSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.marketpredictor.grpc.StrategyService/TrainOnSymbol',
            strategy__service__pb2.TrainingRequest.SerializeToString,
            strategy__service__pb2.TrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchLiveQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.marketpredictor.grpc.StrategyService/FetchLiveQuote',
            strategy__service__pb2.QuoteRequest.SerializeToString,
            strategy__service__pb2.QuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
